# Generated by Django 5.0.3 on 2024-03-21 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('health_on_consume', models.IntegerField(default=0)),
                ('hunger_on_consume', models.IntegerField(default=0)),
                ('thirst_on_consume', models.IntegerField(default=0)),
                ('happiness_on_consume', models.IntegerField(default=0)),
                ('usable', models.BooleanField(default=False)),
                ('consumable', models.BooleanField(default=False)),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='Tamagotchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pogonyalo', models.CharField(max_length=50)),
                ('health', models.IntegerField(default=100)),
                ('hunger', models.IntegerField(default=100)),
                ('thirst', models.IntegerField(default=100)),
                ('happiness', models.IntegerField(default=100)),
                ('is_alive', models.BooleanField(default=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.element')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='TamagotchiInPossession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamagotchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tamagotchi')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tguser')),
            ],
        ),
    ]
