# Generated by Django 4.2.1 on 2024-03-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamagochi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pogonyalo', models.CharField(max_length=50)),
                ('health', models.IntegerField()),
                ('hunger', models.IntegerField()),
                ('thirst', models.IntegerField()),
                ('happiness', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.element')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.rarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('health_on_consume', models.IntegerField(default=0)),
                ('hunger_on_consume', models.IntegerField(default=0)),
                ('thirst_on_consume', models.IntegerField(default=0)),
                ('happiness_on_consume', models.IntegerField(default=0)),
                ('usable', models.BooleanField(default=False)),
                ('consumable', models.BooleanField(default=False)),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.rarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
