# Generated by Django 5.0.3 on 2024-03-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_remove_item_quantity_remove_tamagotchi_happiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamagotchi',
            name='max_happiness',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tamagotchi',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tamagotchi',
            name='max_hunger',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tamagotchi',
            name='max_thirst',
            field=models.IntegerField(default=100),
        ),
    ]
