# Generated by Django 5.0.3 on 2024-03-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_tamagotchi_max_happiness_tamagotchi_max_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='last_page',
            field=models.CharField(default='main', max_length=50),
        ),
    ]
