# Generated by Django 5.0.3 on 2024-03-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_tguser_last_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='max_tamagotchi',
            field=models.IntegerField(default=1),
        ),
    ]
