# Generated by Django 5.0.3 on 2024-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_tguser_max_tamagotchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='last_selected_tamagotchi',
            field=models.IntegerField(default='-1'),
        ),
    ]
