# Generated by Django 5.0.3 on 2024-03-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_tguser_last_selected_tamagotchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='tamagotchi_selected',
            field=models.BooleanField(default=False),
        ),
    ]
