# Generated by Django 5.0.3 on 2024-03-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_tguser_tamagotchi_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tamagotchi_selected',
            new_name='is_tamagotchi_selected',
        ),
    ]
