# Generated by Django 5.0.3 on 2024-03-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_rename_tamagotchi_selected_tguser_is_tamagotchi_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_tamagotchi_renaming',
            field=models.BooleanField(default=False),
        ),
    ]
