# Generated by Django 5.0.3 on 2024-03-24 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_alter_tamagotchiinpossession_happiness_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamagotchiinpossession',
            name='happiness_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tamagotchiinpossession',
            name='health_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tamagotchiinpossession',
            name='hunger_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tamagotchiinpossession',
            name='thirst_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
