# Generated by Django 5.0.3 on 2024-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0013_itemtype_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='is_tamagotchi_renaming',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_message',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='telegram_user_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
