# Generated by Django 5.0.3 on 2024-03-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0014_remove_tguser_is_tamagotchi_renaming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='tamagotchi',
            name='happiness_deprivation',
        ),
        migrations.RemoveField(
            model_name='tamagotchi',
            name='hunger_deprivation',
        ),
        migrations.RemoveField(
            model_name='tamagotchi',
            name='thirst_deprivation',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='happiness_deprivation',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='happiness_update_time',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='health_update_time',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='hunger_deprivation',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='hunger_update_time',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='thirst_deprivation',
        ),
        migrations.RemoveField(
            model_name='tamagotchiinpossession',
            name='thirst_update_time',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='last_message',
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_tamagotchi_renaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='telegram_user_id',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
