# Generated by Django 5.0.3 on 2024-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0015_remove_item_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='is_tamagotchi_renaming',
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_message',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='telegram_user_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
