# Generated by Django 5.0.3 on 2024-03-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0016_remove_tguser_is_tamagotchi_renaming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_need_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsForAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.action')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.item')),
            ],
        ),
        migrations.CreateModel(
            name='RewardForTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.item')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.task')),
            ],
        ),
    ]
