# Generated by Django 5.0.3 on 2024-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0017_action_task_itemsforaction_rewardfortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_item_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_selected_item',
            field=models.IntegerField(default='-1'),
        ),
    ]
