# Generated by Django 5.0.6 on 2024-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0020_tamagotchiinpossession_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='last_selected_task',
            field=models.IntegerField(default=-1),
        ),
    ]
