# Generated by Django 5.0.6 on 2024-05-09 11:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0021_tguser_last_selected_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='current_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.task'),
        ),
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='task_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 8, 12, 57, 332793, tzinfo=datetime.timezone.utc)),
        ),
    ]
