# Generated by Django 5.0.6 on 2024-05-09 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0022_tamagotchiinpossession_current_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamagotchiinpossession',
            name='task_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 8, 37, 53, 313033, tzinfo=datetime.timezone.utc)),
        ),
    ]
