# Generated by Django 5.0.6 on 2024-05-09 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0023_alter_tamagotchiinpossession_task_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='happiness_drop_rate_per_hour',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='health_drop_rate_per_hour',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='hunger_drop_rate_per_hour',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='stats_update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 10, 41, 32, 131942, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tamagotchiinpossession',
            name='thirst_drop_rate_per_hour',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tamagotchiinpossession',
            name='task_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 10, 41, 32, 131942, tzinfo=datetime.timezone.utc)),
        ),
    ]
